{% set version = "0.8.0" %}

package:
  name: optimas
  version: {{ version }}

source:
  url: https://github.com/optimas-org/optimas/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bb57dfbfc17db6da938d9c42c8ac229db093c27e1562d9a1851ddf5350df5d0e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - ax-platform =0.5.0
    - jinja2
    - libensemble
    - mpi4py
    - python >=3.10
    - numpy
    - matplotlib-base

test:
  imports:
    - optimas

about:
  home: https://optimas.readthedocs.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: license.txt
  summary: Optimization at scale, powered by libEnsemble

  description: |
    Optimas is a Python library designed for highly scalable optimization, from
    laptops to massively-parallel supercomputers.
    Key Features
    Scalability: Leveraging the power of libEnsemble, Optimas is designed to
                 scale seamlessly from your laptop to high-performance computing
                 clusters.
    User-Friendly: Optimas simplifies the process of running large parallel
                   parameter scans and optimizations. Specify the number of
                   parallel evaluations and the computing resources to allocate
                   to each of them and Optimas will handle the rest.
    Advanced Optimization: Optimas integrates algorithms from the Ax library,
                           offering both single- and multi-objective Bayesian
                           optimization. This includes advanced techniques such
                           as multi-fidelity and multi-task algorithms.
  dev_url: https://github.com/optimas-org/optimas

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
    - RemiLehe
